name: Compile less -> css
on:
  push:
    branches:
      - josh/add-actions

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - uses: NaturalHistoryMuseum/compile-frontend-actions/less@v1.1.0
        id: less
        with:
          target: 'ckanext/nhm/theme/less/*.less'
          destination: 'ckanext/nhm/theme/fanstatic/css/'

      - name: Commit changes and push
        if: steps.less.outputs.modified != '[]'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MODIFIED: ${{ steps.less.outputs.modified }}
        run: |
          git config user.name "Compile action on behalf of $GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git checkout `echo $GITHUB_REF | cut -d'/' -f3-`
          git add `echo $MODIFIED | jq -r 'join(" ")'`
          git commit -m "[bot] Update production frontend files"
          git push "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git" `echo $GITHUB_REF | cut -d'/' -f3-`
