dist: trusty
language: python

python:
  - "2.7"

install:
  - sh ckanext/nhm/tests/bin/build.sh

services:
  - redis-server
  - postgresql

addons:
  postgresql: "9.4"

script: coverage run --source=ckanext.nhm setup.py nosetests --ckan --with-pylons=ckanext/nhm/tests/bin/test.ini --nologcapture --debug=ckantest,ckanext.nhm --rednose

after_success: coveralls
