version: "3"

services:
  ckan:
    build:
      context: .
      dockerfile: docker/Dockerfile
    environment:
      PYTHONUNBUFFERED: 1
      PYTHONDONTWRITEBYTECODE: 1
    depends_on:
      - db
      - solr
      - redis
      - elasticsearch
      - mongodb
    volumes:
      - ./ckanext:/base/src/ckanext-nhm/ckanext
      - ./tests:/base/src/ckanext-nhm/tests

  solr:
    image: ckan/ckan-solr:2.9
    logging:
      driver: none

  db:
    build:
      context: https://github.com/okfn/docker-ckan.git#:postgresql
      args:
        - DATASTORE_READONLY_PASSWORD=password
        - POSTGRES_PASSWORD=password
    environment:
      - DATASTORE_READONLY_PASSWORD=password
      - POSTGRES_PASSWORD=password
      - PGDATA=/var/lib/postgresql/data/db
    logging:
      driver: none

  redis:
    image: redis:latest
    logging:
      driver: none

  elasticsearch:
    image: elasticsearch:8.17.4
    environment:
      ES_JAVA_OPTS: -Xms2g -Xmx2g
      discovery.type: single-node
      cluster.name: nhm-test
      node.name: nhm-test-one
      network.bind_host: 0.0.0.0
      network.host: 0.0.0.0
      cluster.routing.allocation.disk.threshold_enabled: "false"
      # this ensures we can connect over http
      xpack.security.enabled: "false"
      # this allows our tests to delete indexes using a wildcard
      action.destructive_requires_name: "false"

  mongodb:
    image: mongo:6.0.21
